#!/usr/bin/env fish
set REPONAME $argv[1]
set GITLAB_URL "git@gitlab.com:ninpnin/$REPONAME.git"
set GITHUB_URL "git@github.com:ninpnin/$REPONAME.git"
git clone --origin gitlab $GITLAB_URL
cd $REPONAME
git remote add github $GITHUB_URL
cd ..